/*
 * generated by Xtext 2.9.1
 */
package de.grewe.vuc.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MgplProposalProvider extends AbstractMgplProposalProvider {
}
