/*
 * generated by Xtext 2.9.1
 */
package de.grewe.vuc.validation

import org.eclipse.xtext.validation.Check
import de.grewe.vuc.mgpl.MgplPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MgplValidator extends AbstractMgplValidator {
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MgplPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
